title: "PureShine Autodetailing"
description: "Korekta lakieru • Powłoki ceramiczne • Detailing wnętrza"
remote_theme: "mmistakes/minimal-mistakes"

# Skórka (wygląd kolorystyczny) – możesz zmienić np. na "dark", "mint"
minimal_mistakes_skin: "default"

# GitHub Pages – działające wtyczki
plugins:
  - jekyll-include-cache
  - jekyll-paginate

# Ważne dla User Site (twoj-login.github.io)
url: "https://PureShine123.github.io"
baseurl: ""   # <- puste, bo to strona użytkownika

locale: "pl"

# Autor – pojawi się w sidebarze i na dole
author:
  name: "PureShine Detailing"
  avatar: "/assets/images/avatar.jpg" # wrzuć swój plik
  bio: "Przywracamy blask Twojemu samochodowi 🚗✨"
  location: "Elbląg"
  links:
    - label: "Instagram"
      icon: "fab fa-instagram"
      url: "https://www.instagram.com/detailing_pureshine_elblag?fbclid=IwY2xjawMTGDZleHRuA2FlbQIxMABicmlkETE0bENVUHV1T0kyaGN6MUQ4AR5lbWK6QyfSKm4Kvv-ednqUAl5qntj5YOwUZYwYvBHkJzIXexSv-DZ9jKcIsg_aem_POtAQWOLXHE4M5E3FJlM4Q"
    - label: "Facebook"
      icon: "fab fa-facebook"
      url: "https://www.facebook.com/p/Pure-Shine-Elbl%C4%85g-61562244935278/"
    - label: "Telefon"
      icon: "fas fa-phone"
      url: "tel:+48606860617"

# Menu górne (masthead)
navigation:
  - title: "Start"
    url: /
  - title: "Usługi"
    url: /uslugi/
  - title: "Realizacje"
    url: /realizacje/
  - title: "Cennik"
    url: /cennik/
  - title: "Kontakt"
    url: /kontakt/

# Strona główna z listą postów (jak w demie)
paginate: 6
paginate_path: "/page:num/"

# Okruszki i wyszukiwarka
breadcrumbs: true
search: true

# Stopka (sociale na dole strony)
footer:
  links:
    - label: "Instagram"
      icon: "fab fa-instagram"
      url: "https://www.instagram.com/detailing_pureshine_elblag?fbclid=IwY2xjawMTGDZleHRuA2FlbQIxMABicmlkETE0bENVUHV1T0kyaGN6MUQ4AR5lbWK6QyfSKm4Kvv-ednqUAl5qntj5YOwUZYwYvBHkJzIXexSv-DZ9jKcIsg_aem_POtAQWOLXHE4M5E3FJlM4Q"
    - label: "Facebook"
      icon: "fab fa-facebook"
      url: "https://www.facebook.com/p/Pure-Shine-Elbl%C4%85g-61562244935278/"
